import { existsSync, mkdirSync, readdirSync, statSync, copyFileSync, writeFileSync } from 'node:fs'
import { extname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))

const sources = [
  { dir: join(root, 'rucvfile'), outBase: 'resume-ru', locale: 'ru' },
  { dir: join(root, 'engcvfile'), outBase: 'resume-en', locale: 'en' },
]

const publicDir = join(root, 'public')
if (!existsSync(publicDir)) mkdirSync(publicDir, { recursive: true })

const links = { ru: '/resume-ru.pdf', en: '/resume-en.pdf' }

for (const { dir, outBase, locale } of sources) {
  if (!existsSync(dir)) {
    console.warn(`[sync-resumes] ${dir} not found, skipping (keeping existing public/${outBase}.*)`)
    continue
  }

  const candidates = readdirSync(dir)
    .filter((name) => !name.startsWith('.') && statSync(join(dir, name)).isFile())
    .map((name) => ({ name, mtime: statSync(join(dir, name)).mtimeMs }))
    .sort((a, b) => b.mtime - a.mtime)

  if (candidates.length === 0) {
    console.warn(`[sync-resumes] no file found in ${dir}, skipping`)
    continue
  }

  const { name } = candidates[0]
  const ext = extname(name) || '.pdf'
  const outName = `${outBase}${ext}`
  copyFileSync(join(dir, name), join(publicDir, outName))
  links[locale] = `/${outName}`
  console.log(`[sync-resumes] ${dir}/${name} -> public/${outName}`)
}

writeFileSync(
  join(root, 'src', 'data', 'resumeLinks.generated.ts'),
  `// Auto-generated by scripts/sync-resumes.mjs — do not edit by hand.\nexport const resumeLinks = ${JSON.stringify(links, null, 2)}\n`,
)
